version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: cinebattle-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ab12c3
      MYSQL_DATABASE: cinebattle
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
